name: mariadb
summary: "Database engine"
description: "A pretty popular database"
provides:
  server:
    interface: mysql
  server-admin:
    interface: mysql-root
resources:
  mysql_image:
    type: "oci-image"
    description: "Image used for mysql pod."
  another_image:
    type: "oci-image"
    description: "Image used for unit test results."
series:
  - kubernetes
