name: storage-filesystem
summary: A charm needing filesystem storage
description: See above
storage:
    data:
        type: filesystem
        read-only: true
        multiple:
          range: 1+
    cache:
        type: filesystem
        multiple:
          range: 0+
series:
  - kubernetes
